// Stale ID, zeby ponowny seed nadpisywal, a nie duplikowal.

export const SEED_CATEGORIES = [
  { id: "cat_muzyka", name: "MUZYKA", color: "#ff2d78" },
  { id: "cat_film", name: "FILM & TV", color: "#23e0c8" },
  { id: "cat_nauka", name: "NAUKA", color: "#ffd23f" },
  { id: "cat_historia", name: "HISTORIA", color: "#7c5cff" },
  { id: "cat_geografia", name: "GEOGRAFIA", color: "#3fa7ff" },
  { id: "cat_popkultura", name: "POPKULTURA", color: "#ff7a2d" },
  // Kategoria finalowa — uzywana TYLKO w rundzie "Szacowanie".
  { id: "cat_szacowanie", name: "SZACOWANIE", color: "#00e676", final: true },
];

const opt = (id, text) => ({ id, text });

// Pytanie szacowania: type "estimate", estimateType: integer|float|time,
// correctValue liczbowo (dla time = minuty od polnocy).
const est = (id, text, estimateType, correctValue, unit) => ({
  id, categoryId: "cat_szacowanie", type: "estimate", text,
  media: null, options: [], correctOptionId: null, correctAnswer: "",
  estimateType, correctValue, unit: unit || "",
});

export const SEED_QUESTIONS = [
  {
    id: "q01",
    categoryId: "cat_muzyka",
    type: "closed",
    text: "Ktory zespol nagral album 'The Dark Side of the Moon' (1973)?",
    media: null,
    options: [opt("a", "Led Zeppelin"), opt("b", "Pink Floyd"), opt("c", "The Doors"), opt("d", "Genesis")],
    correctOptionId: "b",
    correctAnswer: "",
  },
  {
    id: "q02",
    categoryId: "cat_muzyka",
    type: "open",
    text: "Jak nazywa sie wokalista grupy Queen (imie i nazwisko)?",
    media: null,
    options: [],
    correctOptionId: null,
    correctAnswer: "Freddie Mercury",
  },
  {
    id: "q03",
    categoryId: "cat_film",
    type: "closed",
    text: "W ktorym roku do kin trafil pierwszy film 'Matrix'?",
    media: null,
    options: [opt("a", "1997"), opt("b", "1999"), opt("c", "2001"), opt("d", "2003")],
    correctOptionId: "b",
    correctAnswer: "",
  },
  {
    id: "q04",
    categoryId: "cat_film",
    type: "open",
    text: "Kto wyrezyserowal film 'Pulp Fiction'?",
    media: null,
    options: [],
    correctOptionId: null,
    correctAnswer: "Quentin Tarantino",
  },
  {
    id: "q05",
    categoryId: "cat_nauka",
    type: "closed",
    text: "Jaki pierwiastek ma symbol chemiczny 'Au'?",
    media: null,
    options: [opt("a", "Srebro"), opt("b", "Glin"), opt("c", "Zloto"), opt("d", "Miedz")],
    correctOptionId: "c",
    correctAnswer: "",
  },
  {
    id: "q06",
    categoryId: "cat_nauka",
    type: "closed",
    text: "Ktora planeta Ukladu Slonecznego jest najwieksza?",
    media: { type: "image", url: "https://picsum.photos/seed/planet/960/540" },
    options: [opt("a", "Saturn"), opt("b", "Neptun"), opt("c", "Ziemia"), opt("d", "Jowisz")],
    correctOptionId: "d",
    correctAnswer: "",
  },
  {
    id: "q07",
    categoryId: "cat_nauka",
    type: "open",
    text: "Ile wynosi przyblizona predkosc swiatla w prozni w km/s?",
    media: null,
    options: [],
    correctOptionId: null,
    correctAnswer: "300000",
  },
  {
    id: "q08",
    categoryId: "cat_historia",
    type: "closed",
    text: "W ktorym roku rozpoczela sie II wojna swiatowa?",
    media: null,
    options: [opt("a", "1914"), opt("b", "1939"), opt("c", "1945"), opt("d", "1918")],
    correctOptionId: "b",
    correctAnswer: "",
  },
  {
    id: "q09",
    categoryId: "cat_historia",
    type: "open",
    text: "Kto byl pierwszym czlowiekiem na Ksiezycu?",
    media: null,
    options: [],
    correctOptionId: null,
    correctAnswer: "Neil Armstrong",
  },
  {
    id: "q10",
    categoryId: "cat_geografia",
    type: "closed",
    text: "Stolica Australii to:",
    media: null,
    options: [opt("a", "Sydney"), opt("b", "Melbourne"), opt("c", "Canberra"), opt("d", "Perth")],
    correctOptionId: "c",
    correctAnswer: "",
  },
  {
    id: "q11",
    categoryId: "cat_geografia",
    type: "open",
    text: "Najdluzsza rzeka swiata (nazwa)?",
    media: null,
    options: [],
    correctOptionId: null,
    correctAnswer: "Nil",
  },
  {
    id: "q12",
    categoryId: "cat_popkultura",
    type: "closed",
    text: "Jak nazywa sie zolty, gabczasty bohater kreskowki mieszkajacy w ananasie?",
    media: null,
    options: [opt("a", "Patryk"), opt("b", "SpongeBob"), opt("c", "Squidward"), opt("d", "Pan Krab")],
    correctOptionId: "b",
    correctAnswer: "",
  },

  // --- Dodatkowe pytania (wieksza pula do walki o terytorium) ---
  { id: "q13", categoryId: "cat_muzyka", type: "closed", text: "Ktory instrument ma 88 klawiszy?", media: null,
    options: [opt("a","Akordeon"),opt("b","Fortepian"),opt("c","Organy"),opt("d","Klawesyn")], correctOptionId: "b", correctAnswer: "" },
  { id: "q14", categoryId: "cat_muzyka", type: "closed", text: "Z jakiego kraju pochodzi zespol ABBA?", media: null,
    options: [opt("a","Norwegia"),opt("b","Szwecja"),opt("c","Dania"),opt("d","Finlandia")], correctOptionId: "b", correctAnswer: "" },
  { id: "q15", categoryId: "cat_film", type: "closed", text: "Kto gra glowna role w filmie 'Forrest Gump'?", media: null,
    options: [opt("a","Tom Hanks"),opt("b","Tom Cruise"),opt("c","Brad Pitt"),opt("d","Kevin Costner")], correctOptionId: "a", correctAnswer: "" },
  { id: "q16", categoryId: "cat_film", type: "closed", text: "Jak nazywa sie fikcyjne miasto Batmana?", media: null,
    options: [opt("a","Metropolis"),opt("b","Gotham"),opt("c","Star City"),opt("d","Central City")], correctOptionId: "b", correctAnswer: "" },
  { id: "q17", categoryId: "cat_nauka", type: "closed", text: "Ile kosci ma dorosly czlowiek?", media: null,
    options: [opt("a","206"),opt("b","180"),opt("c","250"),opt("d","300")], correctOptionId: "a", correctAnswer: "" },
  { id: "q18", categoryId: "cat_nauka", type: "open", text: "Jak nazywa sie najmniejsza jednostka materii zachowujaca wlasciwosci pierwiastka?", media: null,
    options: [], correctOptionId: null, correctAnswer: "atom" },
  { id: "q19", categoryId: "cat_historia", type: "closed", text: "Kto byl pierwszym krolem Polski?", media: null,
    options: [opt("a","Mieszko I"),opt("b","Boleslaw Chrobry"),opt("c","Kazimierz Wielki"),opt("d","Wladyslaw Lokietek")], correctOptionId: "b", correctAnswer: "" },
  { id: "q20", categoryId: "cat_historia", type: "closed", text: "W ktorym roku czlowiek pierwszy raz stanal na Ksiezycu?", media: null,
    options: [opt("a","1965"),opt("b","1969"),opt("c","1972"),opt("d","1959")], correctOptionId: "b", correctAnswer: "" },
  { id: "q21", categoryId: "cat_geografia", type: "closed", text: "Na ktorym kontynencie lezy Egipt?", media: null,
    options: [opt("a","Azja"),opt("b","Afryka"),opt("c","Europa"),opt("d","Ameryka Pld.")], correctOptionId: "b", correctAnswer: "" },
  { id: "q22", categoryId: "cat_geografia", type: "open", text: "Jak nazywa sie najwyzszy szczyt swiata?", media: null,
    options: [], correctOptionId: null, correctAnswer: "Mount Everest" },
  { id: "q23", categoryId: "cat_popkultura", type: "closed", text: "Jak nazywa sie czarodziej z Hogwartu z blizna na czole?", media: null,
    options: [opt("a","Ron Weasley"),opt("b","Harry Potter"),opt("c","Draco Malfoy"),opt("d","Neville")], correctOptionId: "b", correctAnswer: "" },
  { id: "q24", categoryId: "cat_popkultura", type: "closed", text: "W ktorej grze zbierasz klocki i budujesz swiaty z blokow?", media: null,
    options: [opt("a","Fortnite"),opt("b","Minecraft"),opt("c","Roblox"),opt("d","Terraria")], correctOptionId: "b", correctAnswer: "" },

  // --- Pytania finalowe: SZACOWANIE (odpowiedzi liczbowe) ---
  est("est01", "Ile lat ma Wieza Eiffla w 2025 roku? (rok budowy 1889)", "integer", 136, "lat"),
  est("est02", "Ile kilometrow ma rownik Ziemi? (w tysiacach km)", "float", 40.075, "tys. km"),
  est("est03", "O ktorej godzinie (czas srodkowoeuropejski) Slonce gornuje ok. 21 czerwca w Warszawie?", "time", 750, "godz"),
  est("est04", "Ile wynosi srednia temperatura ciala czlowieka w stopniach Celsjusza?", "float", 36.6, "°C"),
  est("est05", "Ile panstw jest czlonkami ONZ (stan na 2024)?", "integer", 193, "panstw"),
  est("est06", "O ktorej godzinie zaczyna sie doba? (00:00)", "time", 0, "godz"),
];
