// Stale ID, zeby ponowny seed nadpisywal, a nie duplikowal.

export const SEED_CATEGORIES = [
  { id: "cat_muzyka", name: "MUZYKA", color: "#ff2d78" },
  { id: "cat_film", name: "FILM & TV", color: "#23e0c8" },
  { id: "cat_nauka", name: "NAUKA", color: "#ffd23f" },
  { id: "cat_historia", name: "HISTORIA", color: "#7c5cff" },
  { id: "cat_geografia", name: "GEOGRAFIA", color: "#3fa7ff" },
  { id: "cat_popkultura", name: "POPKULTURA", color: "#ff7a2d" },
];

const opt = (id, text) => ({ id, text });

export const SEED_QUESTIONS = [
  {
    id: "q01",
    categoryId: "cat_muzyka",
    type: "closed",
    text: "Ktory zespol nagral album 'The Dark Side of the Moon' (1973)?",
    media: null,
    options: [opt("a", "Led Zeppelin"), opt("b", "Pink Floyd"), opt("c", "The Doors"), opt("d", "Genesis")],
    correctOptionId: "b",
    correctAnswer: "",
  },
  {
    id: "q02",
    categoryId: "cat_muzyka",
    type: "open",
    text: "Jak nazywa sie wokalista grupy Queen (imie i nazwisko)?",
    media: null,
    options: [],
    correctOptionId: null,
    correctAnswer: "Freddie Mercury",
  },
  {
    id: "q03",
    categoryId: "cat_film",
    type: "closed",
    text: "W ktorym roku do kin trafil pierwszy film 'Matrix'?",
    media: null,
    options: [opt("a", "1997"), opt("b", "1999"), opt("c", "2001"), opt("d", "2003")],
    correctOptionId: "b",
    correctAnswer: "",
  },
  {
    id: "q04",
    categoryId: "cat_film",
    type: "open",
    text: "Kto wyrezyserowal film 'Pulp Fiction'?",
    media: null,
    options: [],
    correctOptionId: null,
    correctAnswer: "Quentin Tarantino",
  },
  {
    id: "q05",
    categoryId: "cat_nauka",
    type: "closed",
    text: "Jaki pierwiastek ma symbol chemiczny 'Au'?",
    media: null,
    options: [opt("a", "Srebro"), opt("b", "Glin"), opt("c", "Zloto"), opt("d", "Miedz")],
    correctOptionId: "c",
    correctAnswer: "",
  },
  {
    id: "q06",
    categoryId: "cat_nauka",
    type: "closed",
    text: "Ktora planeta Ukladu Slonecznego jest najwieksza?",
    media: { type: "image", url: "https://picsum.photos/seed/planet/960/540" },
    options: [opt("a", "Saturn"), opt("b", "Neptun"), opt("c", "Ziemia"), opt("d", "Jowisz")],
    correctOptionId: "d",
    correctAnswer: "",
  },
  {
    id: "q07",
    categoryId: "cat_nauka",
    type: "open",
    text: "Ile wynosi przyblizona predkosc swiatla w prozni w km/s?",
    media: null,
    options: [],
    correctOptionId: null,
    correctAnswer: "300000",
  },
  {
    id: "q08",
    categoryId: "cat_historia",
    type: "closed",
    text: "W ktorym roku rozpoczela sie II wojna swiatowa?",
    media: null,
    options: [opt("a", "1914"), opt("b", "1939"), opt("c", "1945"), opt("d", "1918")],
    correctOptionId: "b",
    correctAnswer: "",
  },
  {
    id: "q09",
    categoryId: "cat_historia",
    type: "open",
    text: "Kto byl pierwszym czlowiekiem na Ksiezycu?",
    media: null,
    options: [],
    correctOptionId: null,
    correctAnswer: "Neil Armstrong",
  },
  {
    id: "q10",
    categoryId: "cat_geografia",
    type: "closed",
    text: "Stolica Australii to:",
    media: null,
    options: [opt("a", "Sydney"), opt("b", "Melbourne"), opt("c", "Canberra"), opt("d", "Perth")],
    correctOptionId: "c",
    correctAnswer: "",
  },
  {
    id: "q11",
    categoryId: "cat_geografia",
    type: "open",
    text: "Najdluzsza rzeka swiata (nazwa)?",
    media: null,
    options: [],
    correctOptionId: null,
    correctAnswer: "Nil",
  },
  {
    id: "q12",
    categoryId: "cat_popkultura",
    type: "closed",
    text: "Jak nazywa sie zolty, gabczasty bohater kreskowki mieszkajacy w ananasie?",
    media: null,
    options: [opt("a", "Patryk"), opt("b", "SpongeBob"), opt("c", "Squidward"), opt("d", "Pan Krab")],
    correctOptionId: "b",
    correctAnswer: "",
  },
];
